# Generated by Django 5.1.7 on 2025-04-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefas',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
