# Generated by Django 5.1.7 on 2025-04-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_rename_create_at_tarefas_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='descricão',
            field=models.TextField(),
        ),
    ]
